
export const WISHLIST = {
  ADD_TO_WISHLIST: "ADD_TO_WISHLIST",
  REMOVE_FROM_WISHLIST: "REMOVE_FROM_WISHLIST",
};

export const FOLLOWING = {
  ADD_TO_FOLLOWING: "ADD_TO_FOLLOWING",
  REMOVE_FROM_FOLLOWING: "REMOVE_FROM_FOLLOWING",
};

export const TOPIC = {
  ADD_TO_TOPIC: "ADD_TO_TOPIC",
  REMOVE_FROM_TOPIC: "REMOVE_FROM_TOPIC",
};

export const USER = {
  SET_USER_DETAILS: "SET_USER_DETAILS",
  CLEAR_USER_DETAILS: "CLEAR_USER_DETAILS",
};
